[uv]
env = "transport"
python = "3.11"

[packages]
numpy = "^1.26.0"
gurobipy = "^10.0.0"
pandas = { version = "^2.1.1", extras = ["excel"] }
plotly = "^5.16.1"
matplotlib = "^3.8.0"
ipykernel = "^6.25.1"
ipympl = "^0.9.3"
